server:
  port: 8088
  servlet:
    context-path: /svm

spring:
  datasource:
    security:
      filters: stat
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/svm
      username: security
      password: security
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select current_date
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
    sample:
      filters: stat
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/svm
      username: sample
      password: sample
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select current_date
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


logging:
  config: classpath:logback-spring.xml
  logdir: e:/temp/log

app:
  allowedCors: http://localhost:8080