package svm.sample.entity;

public class CityDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_city.city_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    private Short cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_city.city_name
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_city.province_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    private Short provinceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_city.city_id
     *
     * @return the value of sample_city.city_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public Short getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_city.city_id
     *
     * @param cityId the value for sample_city.city_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_city.city_name
     *
     * @return the value of sample_city.city_name
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_city.city_name
     *
     * @param cityName the value for sample_city.city_name
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_city.province_id
     *
     * @return the value of sample_city.province_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public Short getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_city.province_id
     *
     * @param provinceId the value for sample_city.province_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public void setProvinceId(Short provinceId) {
        this.provinceId = provinceId;
    }
}