package svm.sample.entity;

public class ProvinceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_province.province_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    private Short provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_province.province_name
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    private String provinceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_province.province_id
     *
     * @return the value of sample_province.province_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public Short getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_province.province_id
     *
     * @param provinceId the value for sample_province.province_id
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public void setProvinceId(Short provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_province.province_name
     *
     * @return the value of sample_province.province_name
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_province.province_name
     *
     * @param provinceName the value for sample_province.province_name
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }
}