logging:
  level:
    root: info

spring:
  datasource:
    filters: stat
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/svm
    username: sample
    password: 4383C350B169944F
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 10000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select current_date
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

app:
  allowedCors: http://localhost:8080
  sessionTimeout: -1