package svm.sample.dao;

import svm.sample.entity.CityDO;

public interface CityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_city
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int deleteByPrimaryKey(Short cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_city
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int insert(CityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_city
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int insertSelective(CityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_city
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    CityDO selectByPrimaryKey(Short cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_city
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int updateByPrimaryKeySelective(CityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_city
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int updateByPrimaryKey(CityDO record);
}