package svm.sample.dao;

import svm.sample.entity.ProvinceDO;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_province
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int deleteByPrimaryKey(Short provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_province
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int insert(ProvinceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_province
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int insertSelective(ProvinceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_province
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    ProvinceDO selectByPrimaryKey(Short provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_province
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int updateByPrimaryKeySelective(ProvinceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_province
     *
     * @mbg.generated Thu Nov 15 16:50:54 CST 2018
     */
    int updateByPrimaryKey(ProvinceDO record);
}